### PR TITLE
Resolves #6 by correctly passing the '-verb' argument

### LINKED ISSUE #6: Unrecognized argument 'verb:sync'. All arguments must begin with "-".
Using version 0.1.2 and get this error.

### PR DESCRIPTION
**Pull request by ecampidoglio**
This PR resolves #6 by correcting the way the `-verb` argument is passed to `msdeploy.exe`.

### CODE REVIEW

**Comment by calaa** [comment]
@ecampidoglio Thanks for the PR! Now just have to wait until it gets accepted 😄

**Comment by gep13** [comment]
@ecampidoglio looks good to me, but I will wait for @louisfischer to have a look as well before merging.

@ecampidoglio just one quick point, although not expressed for each repo in this repository, I think all repos in the Cake-Contrib organisation will end up following the contribution guidelines that Cake follows, namely:

https://github.com/cake-build/cake/blob/develop/CONTRIBUTING.md

For future PR's, can I ask that PR are done on a feature/topic branch?

**Comment by ecampidoglio** [comment]
@gep13
> For future PR's, can I ask that PR are done on a feature/topic branch?

Sure, no problem 👍

**Comment by louisfischer** [comment]
Looks good to me...

**Comment by louisfischer** [comment]
0.1.4 has been released to NuGet. Thanks again for the the fix.

**Pull request merged**
