### PR TITLE
Update Version of cake to 0.26.1

### PR DESCRIPTION
**Pull request by louisfischer**
Update Version of cake to 0.26.0

### CODE REVIEW

**Comment by gep13** [comment]
Relates to #29

**Comment by sheriffjohn** [comment]
Is it possible to rerun this? We need this fix for our MSDeploys.

**Comment by louisfischer** [comment]
@sheriffjohn the build is failing for some reason related to Error: Failed to install addin 'Cake.Codecov'.. I will take a look at it later tonight after I am off work

**Comment by louisfischer** [comment]
relates to #31

**Pull request merged**
